### ISSUE TITLE
Add NuGet support

### ISSUE THREAD

**Issue by kanema** [greengerong/Prerender_asp_mvc#11]
I took the liberty of putting the package available via nuget.
To do this i change the namespace from Prerender_asp_net to Prerender.io.
https://www.nuget.org/packages/Prerender.io/
Maybe ia a good idea divide in two projects, the module and the demo.

**Comment by RodH257** [comment]
Thought I'd +1 getting the nuget package updated, I just got tripped up by the differences as the nuget package wasn't working correctly for me (not sending through escaped_fragment to the prerender service) but building from source works correctly, so I guess it's something that was changed after the nuget package was generated. Not sure if there's any way I can help with this, I guess the owner on nuget.org needs to manage it?

**Comment by thoop** [comment]
I tried to contact @kanema about updating the nuget package but never heard back. Maybe the ping on github will do the trick :)

**Comment by greengerong** [comment]
Long  time no response. I think we can close.
