### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by matiastucci** [greengerong/Prerender_asp_mvc#16]
Hi, I have everything already installed but when I build the project it's a blank page. 

I read in the [pretender.io] site that is a common problem get `<html><head></head><body></body></html>` and that: *You are probably on Rails or some other framework that uses blocking I/O*

I am having this issue on a .NET app and I think that it doesn't use blocking I/O. Do you know what can be happening?

Thanks!

[pretender.io]: https://prerender.io/documentation/test-it

**Comment by thoop** [comment]
Hi @matiastucci, are you running a Prerender server locally or are you using our hosted service at https://prerender.io ?

If you are using our hosted service, send me an email at todd@prerender.io and I can help you with debugging this. If you are hosting the server locally, are you seeing any console output from the Prerender server?

**Comment by matiastucci** [comment]
Hi @thoop, I've already sent you an email. Thanks!

**Comment by greengerong** [comment]
Any update? @thoop @matiastucci ?

**Comment by thoop** [comment]
I think you can close this as they changed to use a different middleware

**Comment by greengerong** [comment]
Thanks
