### ISSUE TITLE
Add gzip support

### ISSUE THREAD

**Issue by thoop** [greengerong/Prerender_asp_mvc#4]
The latest version of the Prerender server will return gzipped content to the middleware if the `Accept-Encoding: gzip` header is provided.

In our Node/Rails middleware, we currently always send the `Accept-Encoding: gzip` header and always unzip the response when it comes back from the server. That way, we save on bandwidth.

Supporting gzip with the ASP.NET middleware would be great! You could also decide to not unzip the response if the user sent the `Accept-Encoding: gzip` header in order to leave it compressed.

**Comment by greengerong** [comment]
Done   [https://github.com/greengerong/Prerender_asp_mvc/blob/master/Prerender.io/PrerenderModule.cs#L59](https://github.com/greengerong/Prerender_asp_mvc/blob/master/Prerender.io/PrerenderModule.cs#L59).
