### ISSUE TITLE
 Prerender_asp_mvc stopped working correctly on my website

### ISSUE THREAD

**Issue by shimozurdo** [greengerong/Prerender_asp_mvc#40]
It had been functioning properly about 6 months. But suddenly we noticed that it did not render correctly the meta tags of the page.
![capture](https://user-images.githubusercontent.com/4074823/49889673-bd5cc580-fe07-11e8-8b9a-a80e2a22afd6.JPG)

The only change we made was to redirect to https and our web config is like this.

```
<configuration>
  <configSections>
    <section name="prerender" type="Prerender.io.PrerenderConfigSection, Prerender.io, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />
  </configSections>
  <prerender token="[Token]">
  </prerender>
  <appSettings>
    ...
  </appSettings>
  <system.web>
    <compilation debug="true" targetFramework="4.5.2" />
    <httpRuntime targetFramework="4.5.2" maxUrlLength="2048" />
    <httpModules>
      ...
      <add name="Prerender" type="Prerender.io.PrerenderModule, Prerender.io, Version=1.0.0.2, Culture=neutral, PublicKeyToken=null" />
    </httpModules>
  </system.web>
  <runtime>
    ...
  </runtime>
  <system.webServer>
    <httpProtocol>
      ...
    </httpProtocol>
    <staticContent>
      ...
    </staticContent>
    <rewrite>
      <rules>
        <rule name="httpsredirect" stopProcessing="true">
          <match url="(.*)" />
          <conditions>
            <add input="{HTTPS}" pattern="off" ignoreCase="true" />
          </conditions>
          <action type="Redirect" redirectType="Permanent" url="https://{HTTP_HOST}/{R:1}" />
        </rule>
      </rules>
    </rewrite>
    <security>
      <requestFiltering allowDoubleEscaping="true" />
    </security>
    <validation validateIntegratedModeConfiguration="false" />
    <modules>
      ...
    </modules>
  </system.webServer>
  <system.codedom>
    ..
  </system.codedom>
</configuration>

```

We went back to update the library from nuget package, we even downloaded the project and compiled it and used the dll and it has not worked again.

Note:
the urls of the site do not use # or !# They appear like these _https://github.com/vinaygopinath/ngMeta_ for example.

 using this in angularjs router
` $locationProvider.html5Mode(true);`
and 
`<base href="/" />` in th html

I reiterate, the project before worked properly, which means that it was configured correctly, as indicated in the tutorial, but now it no longer render the code js in the searches.

Any suggestions? Thanks in advance.

**Comment by thoop** [comment]
I'm seeing some javascript errors on your site that prevent it from loading at all:

![image](https://user-images.githubusercontent.com/1259374/49899819-0e75b500-fe1a-11e8-8b12-483c67f24bd5.png)

It looks like that is what is being served back to Facebook. Can you make sure your website is loading properly then recache it to see if it saves the correct content?

**Comment by shimozurdo** [comment]
Ok, we did some changes in the code, because of the page had errors, now the issues was fixed. Now i can see the prerender is caching pages again.

![capture](https://user-images.githubusercontent.com/4074823/49905015-cfebf480-fe31-11e8-8f73-588650052bc8.JPG)
 

However only this link "https://solomedicos.org.mx/" shows the complete data in facebook debugger, but not this "https://solomedicos.org.mx/directorio/especialista/4568305-rodolfo-salazar-villa" for example

both has meta tags 

![capture2](https://user-images.githubusercontent.com/4074823/49905380-14c45b00-fe33-11e8-8a6b-674a261903a9.JPG)
![capture3](https://user-images.githubusercontent.com/4074823/49905384-17bf4b80-fe33-11e8-868e-0959368576bc.JPG)


It might take a while to show the full information but I'm not sure.
