### ISSUE TITLE
URL-Rewrite

### ISSUE THREAD

**Issue by blowsie** [greengerong/Prerender_asp_mvc#6]
Just a thought is there a reason this isn't using the IIS re-write module? Did you try and develop using this? Or is there any limitations or reasons this wont work?

http://www.iis.net/downloads/microsoft/url-rewrite

**Comment by sivastyle** [comment]
I am not able to get this working . Can someone help ? I am getting a 500 internal server error when trying the same 

please check here. 
www.vbuy.in/product/samsung-galaxy-grand-2-black-/1975?_escaped_fragment_

**Comment by thoop** [comment]
`http://www.vbuy.in/product/samsung-galaxy-grand-2-black-/1975?_escaped_fragment_=`
is redirecting to:
`http://service.prerender.io/http://www.vbuy.in/product/samsung-galaxy-grand-2-black-/1975?_escaped_fragment_=`
which is incorrect. Something isn't set up right there.

It should proxy behind the scenes to our service without doing a redirect. Send me the config set up that you have at todd@prerender.io and I'll look into why that's happening.

**Comment by sivastyle** [comment]
Todd, we will discuss in mail. Thanks for your continuous support in mail. 

-Siva.

**Comment by greengerong** [comment]
Any update? Can i close this ?

**Comment by thoop** [comment]
I think so. Thanks for your help @greengerong !!
