### ISSUE TITLE
Potentially dangerous request.path

### ISSUE THREAD

**Issue by craigcollie** [greengerong/Prerender_asp_mvc#7]
Having some trouble getting this implemented into my project. As soon as I add the PreApplicationStartMethod to my AssemblyInfo.cs, I get a stack trace of: Potentially dangerous request.path was detected from the client. 

Is there something I need to add to web.config to get this running?

**Comment by sant123** [comment]
@craigcollie What did you do for fixing the issue? Shoud I do this?

``` xml
<system.web>
    <httpRuntime requestPathInvalidCharacters="<,>,*,%,&,\,?" />
</system.web>
```
See that I removed the colon ':'

or

``` xml
<system.web>
    <httpRuntime requestValidationMode="2.0" />
</system.web>
``` 

Thanks.
